name: paragit_movil
description: "Sistema POS"
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  pdf: ^3.10.8
  printing: ^5.11.1
  http: ^1.1.0
  intl: ^0.19.0
  # ACTUALIZADO A LA VERSIÃ“N CORRECTA:
  dotenv: ^4.2.0 
  provider: ^6.1.1  # <--- ESTA ES LA QUE FALTA

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true